### ISSUE TITLE
您好，会支持多种协议吗？

### ISSUE THREAD

**Issue by HuangDayu** [IoT-Technology/Groza#6]
1. socket
2. mqtt
3. coap
4. http
5. dds

这几种都会支持吗？

**Comment by sanshengshui** [comment]
当前支持Mqtt,Coap,http,socket都会支持

**Comment by HuangDayu** [comment]
好的，那就跟着你一起学习了

**Comment by HuangDayu** [comment]
希望多多完善一下文档，重要的是架构图

**Comment by HuangDayu** [comment]
你好，请问你的mqtt测试工具是哪里下载的呢？
![就是这个](https://img2018.cnblogs.com/blog/1497594/201810/1497594-20181026220537362-1139204975.png)  

我在这个[eclipse 官方下载链接](https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/org.eclipse.paho.ui.app/1.0.2/0)下载下来的，但是报一下错误，我没有解决思路：  
```shell
Caused by: java.lang.IllegalStateException: The System Bundle could not be resolved: Missing Constraint: Bundle-RequiredExecutionEnvironment: J2SE-1.5
```
希望你能帮忙解决一下，或者将你的测试工具上传上来，谢谢了。

**Comment by sanshengshui** [comment]
具体的测试工具，你可以看下下面的网址，根据实际操作系统下载:
https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/org.eclipse.paho.ui.app/1.1.1/

**Comment by HuangDayu** [comment]
查到原因了，是因为我使用了Java12，在我同事的java8机器上可以正常运行

**Comment by Ronrey100** [comment]
可以完善下文档吗？目前支持哪些协议？Socket支持吗？
